services:
  caddy:
    image: caddy:2.10.2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf:/etc/caddy
    networks:
      - reverse-proxy
      - monitoring

networks:
  reverse-proxy:
    external: true
  monitoring:
    external: true
