services:
  authelia:
    image: "authelia/authelia:4.39.20"
    container_name: "authelia"
    volumes:
      - "./config:/config"
    restart: "unless-stopped"
    environment:
      TZ: "Europe/Warsaw"
      PUID: 1000
      PGID: 1000
      UMASK: 002
    depends_on:
      - redis
    networks:
      - authelia
      - reverse-proxy
      - monitoring

  redis:
    image: "redis:alpine"
    container_name: "redis"
    volumes:
      - "./redis:/data"
    restart: "unless-stopped"
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - authelia

networks:
  authelia:
    driver: bridge
  reverse-proxy:
    name: reverse-proxy
  monitoring:
    name: monitoring
