services:
  netflix-household-autovalidator:
    image: phd59fr/netflix-household-autovalidator@sha256:63612185a77e6b4f5d30709ffee37eebfbdb6aa8f2e82264be7cda5d21e5441a
    container_name: netflix-household-autovalidator
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yaml
