services:
  netflix-household-autovalidator:
    image: phd59fr/netflix-household-autovalidator@sha256:1dc980171bb254b1e8707b466d404a976cde2b254c1350933f9da50649413fdd
    container_name: netflix-household-autovalidator
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yaml
