---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

layout:
  Management:
  Media:
  Admin:
  External:
    style: row
    columns: 1

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
