services:
  nginx:
    image: nginx:alpine3.22
    container_name: home-page
    volumes:
      - ./static:/usr/share/nginx/html:ro
    restart: always
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
