services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.7.0
    container_name: homepage
    env_file:
      - .env
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=www.home.io
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
