services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:2025.11"
    user: "1000:1000"
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true
    network_mode: host
#    networks:
#      - reverse-proxy

networks:
  reverse-proxy:
    external: true
