services:
  filebrowser:
    container_name: filebrowser
    image: "filebrowser/filebrowser:v2.42.5"
    # ports:
    # - 8080:80
    volumes:
      - ./filebrowser_data:/srv
      - ./filebrowser_database:/database
      - ./filebrowser_config:/config
    restart: always
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
