services:
  caddy:
    build:
      context: .
      target: caddy
    container_name: caddy
    user: 1000:1000
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./caddy/conf:/etc/caddy
      - ./caddy/logs:/var/log/caddy
    depends_on:
      - crowdsec
    networks:
      - reverse-proxy
      - monitoring
      - nextcloud-aio
      - crowdsec
    env_file:
      - .env
    security_opt:
      - no-new-privileges=true

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.7
    container_name: crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/base-http-scenarios
      - BOUNCER_KEY_CADDY=${CROWDSEC_API_KEY}
    volumes:
      - ./crowdsec/config:/etc/crowdsec
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./caddy/logs:/var/log/caddy:ro
    networks:
      - crowdsec
      - monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true

networks:
  reverse-proxy:
    name: reverse-proxy
  monitoring:
    name: monitoring
  nextcloud-aio:
    name: nextcloud-aio
  crowdsec:
    driver: bridge
