services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.6-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy
