services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
